// <auto-generated />
using Enozom_task.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enozomtask.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Enozom_task.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Sheraton"
                        },
                        new
                        {
                            Id = 2,
                            name = "Helnan"
                        },
                        new
                        {
                            Id = 3,
                            name = "Tolip"
                        });
                });

            modelBuilder.Entity("Enozom_task.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HotelID");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 200m,
                            HotelID = 1,
                            Room = "Double Room Sea View"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 150m,
                            HotelID = 1,
                            Room = "SingleRoom Sea View"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 170m,
                            HotelID = 1,
                            Room = "Double Room City View"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 120m,
                            HotelID = 1,
                            Room = "Single Room City View "
                        },
                        new
                        {
                            Id = 5,
                            Cost = 100m,
                            HotelID = 2,
                            Room = "Double Room Garden View"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 90m,
                            HotelID = 2,
                            Room = "Single Room Garden View"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 120m,
                            HotelID = 2,
                            Room = "Double Room Pool View"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 110m,
                            HotelID = 2,
                            Room = "Single Room Pool View"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 80m,
                            HotelID = 3,
                            Room = "Double Room Standard"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 70m,
                            HotelID = 3,
                            Room = "Single Room Standard"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 100m,
                            HotelID = 3,
                            Room = "Double Room Deluxe"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 95m,
                            HotelID = 3,
                            Room = "Single Room Deluxe"
                        });
                });

            modelBuilder.Entity("Enozom_task.Models.Price", b =>
                {
                    b.HasOne("Enozom_task.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });
#pragma warning restore 612, 618
        }
    }
}
